all:
  children:
    aruba_switches:
      hosts:
        SW_31_CAPULISPAMBA:
          ansible_host: 10.31.99.1
          ansible_user: "{{ vault_credentials.switch1.username }}"
          ansible_password: "{{ vault_credentials.switch1.password }}"
          ansible_connection: network_cli
          ansible_network_os: aruba
          ansible_become: yes

        SW_32_MAYANCELA:
          ansible_host: 10.32.99.1
          ansible_user: "{{ vault_credentials.switch1.username }}"
          ansible_password: "{{ vault_credentials.switch1.password }}"
          ansible_connection: network_cli
          ansible_network_os: aruba
          ansible_become: yes

        SW_33_TTERRESTRE:
          ansible_host: 10.33.99.1
          ansible_user: "{{ vault_credentials.switch2.username }}"
          ansible_password: "{{ vault_credentials.switch2.password }}"
          ansible_connection: network_cli
          ansible_network_os: aruba
          ansible_become: yes

        SW_41_FLAGRANCIA:
          ansible_host: 10.10.57.1
          ansible_user: "{{ vault_credentials.switch2.username }}"
          ansible_password: "{{ vault_credentials.switch2.password }}"
          ansible_connection: network_cli
          ansible_network_os: aruba
          ansible_become: yes
