version: "3.9"
services:
  ansible-aruba:
    container_name: ansible-aruba
    image: ansible-aruba:latest
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - source: user_password
          target: user_password
      args:
        USERNAME: rikuriak
    networks:
      ansible_net:
        ipv4_address: 172.20.1.94
    stdin_open: true
    tty: true
secrets:
  user_password:
    file: ./secrets/password.txt

networks:
  ansible_net:
    driver: macvlan
    driver_opts:
      parent: ens192
    ipam:
      config:
        - subnet: 172.20.1.0/24
          gateway: 172.20.1.1
