# create_admin.yml
---
- name: Crear usuario administrador en switches Aruba
  hosts: aruba_switches
  gather_facts: no
  
  vars_prompt:
    - name: "username"
      prompt: "Ingrese el nombre del nuevo administrador"
      private: no
    
    - name: "user_password"
      prompt: "Ingrese la contraseña del administrador"
      private: yes
      confirm: yes

  tasks:
    - name: Generar hash SHA1 de la contraseña
      command: "echo -n '{{ user_password }}' | sha1sum | cut -d' ' -f1"
      register: password_hash
      delegate_to: localhost

    - name: Configurar usuario administrador
      cli_command:
        command: |
          configure
          aaa authentication local-user "{{ username }}" group "Level-15" password sha1 "{{ password_hash.stdout }}"
          end
          write memory
      register: config_output

    - name: Verificar la creación
      cli_command:
        command: "show running-config | include {{ username }}"
      register: verify_output

    - name: Mostrar resultado
      debug:
        var: verify_output.stdout_lines