# create_user.yml - Versión corregida
---
- name: Crear usuario en switches Aruba
  hosts: aruba_switches
  gather_facts: no
  
  vars_prompt:
    - name: "username"
      prompt: "Ingrese el nombre del nuevo usuario"
      private: no
    
    - name: "user_password"
      prompt: "Ingrese la contraseña del usuario"
      private: yes
      confirm: yes
    
    - name: "privilege_level"
      prompt: "Ingrese el nivel de privilegio (operator/manager/Level-15)"
      private: no
      default: "operator"

  tasks:
    - name: Validar nivel de privilegio
      assert:
        that:
          - privilege_level in ['operator', 'manager', 'Level-15']
        fail_msg: "Nivel de privilegio inválido. Use operator, manager o Level-15"

    - name: Configurar usuario
      cli_command:
        command: "configure terminal"
      register: config_mode

    - name: Crear usuario local
      cli_command:
        command: aaa authentication local-user {{ username }} group {{ privilege_level }} password plaintext {{ user_password }}
      register: create_output

    - name: Guardar configuración
      cli_command:
        command: "write memory"
      register: save_output

    - name: Verificar la creación
      cli_command:
        command: "show running-config | include {{ username }}"
      register: verify_output

    - name: Mostrar resultado
      debug:
        var: verify_output.stdout_lines