---
- name: Test Connection to Aruba Switches
  hosts: aruba_switches
  gather_facts: no
  connection: network_cli
  
  tasks:
    - name: Run show version
      aruba_command:
        command:
          - show version
      register: version_output

    - name: Display version
      debug:
        var: version_output.stdout_lines